name: Fetch Web pages
on:
    issues:
        types:
            - opened
jobs:
    Fetch-and-Save:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: pnpm
            - uses: freeCodeCamp-China/article-webpage-to-markdown-action@v1
              with:
                  newsLink: "${{ github.event.issue.Body }}"
                  markDownFilePath: "./_posts/Article/Translation/"
                  githubToken: ${{ github.token }}

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "${{ github.event.issue.title }}"
